[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.82.1"
  HUGO_BASEURL = "https://chunyunma.me"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
	from = "/teaching/*"
	to = "https://confident-ramanujan-5a911b.netlify.app/:splat"
	status = 200
	force = true
